### ISSUE TITLE
Problem during migration yii migrate/up

### ISSUE THREAD

**Issue by Q1984** [Commifreak/multimatic-web#1]
Hi!

Exception: Unable to locate message source for category 'site'. (/root/multimatic-web/vendor/yiisoft/yii2/i18n/I18N.php:201)
Could you please help what could be the problem?

**Comment by Commifreak** [comment]
You were right. There are several things that were wrong.

Please clear the database and start from scratch, it should work now.

Please be aware, that I dont know if all is still working, the code is not maintained anymore. A quick setup under PHP 7.4 was working though.

**Comment by Q1984** [comment]
Many thanks migration works well now.
![kép](https://user-images.githubusercontent.com/50952023/204096077-43ff5e4d-d22b-48a7-9e16-28be786cc210.png)
I've added my vaillant account user and pass to the db v_user and v_pass but nothing happened.
Is there any advice?

**Comment by Commifreak** [comment]
You have to setup a cronjob that runs every 5 minutes: `php yii harvester/cronjob`. The php command may need to be adjusted to your binary.
